/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Materials */
        get: operations["get_materials_materials__get"];
        put?: never;
        /** Create Material */
        post: operations["create_material_materials__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material By Id */
        get: operations["get_material_by_id_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_materials__material_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory-movements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inventory Movements */
        get: operations["get_inventory_movements_inventory_movements__get"];
        put?: never;
        /** Create Inventory Movement */
        post: operations["create_inventory_movement_inventory_movements__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products */
        get: operations["get_products_products__get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_products__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product By Id */
        get: operations["get_product_by_id_products__product_id__get"];
        put?: never;
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_products__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suppliers */
        get: operations["get_suppliers_suppliers__get"];
        put?: never;
        /** Create Supplier */
        post: operations["create_supplier_suppliers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier By Id */
        get: operations["get_supplier_by_id_suppliers__supplier_id__get"];
        put?: never;
        post?: never;
        /** Delete Supplier */
        delete: operations["delete_supplier_suppliers__supplier_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material Suppliers */
        get: operations["get_material_suppliers_materials__material_id__suppliers_get"];
        /** Replace Material Suppliers */
        put: operations["replace_material_suppliers_materials__material_id__suppliers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/preferred-supplier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferred Supplier */
        get: operations["get_preferred_supplier_materials__material_id__preferred_supplier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{supplier_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier Materials */
        get: operations["get_supplier_materials_suppliers__supplier_id__materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product Materials */
        get: operations["get_product_materials_products__product_id__materials_get"];
        /** Replace Product Materials */
        put: operations["replace_product_materials_products__product_id__materials_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material Products */
        get: operations["get_material_products_materials__material_id__products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/rag/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Knowledge */
        post: operations["search_knowledge_ai_rag_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_ai_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/production-risk/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyze Production Risk */
        get: operations["analyze_production_risk_production_risk_analyze_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/material-impact/analyze/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyze Material Impact */
        get: operations["analyze_material_impact_material_impact_analyze__material_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Purchase Plan */
        get: operations["get_current_purchase_plan_purchase_plans_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Purchase Plans */
        get: operations["get_purchase_plans_purchase_plans__get"];
        put?: never;
        /** Create Purchase Plan */
        post: operations["create_purchase_plan_purchase_plans__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-plans/{purchase_plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Purchase Plan By Id */
        get: operations["get_purchase_plan_by_id_purchase_plans__purchase_plan_id__get"];
        /** Update Purchase Plan */
        put: operations["update_purchase_plan_purchase_plans__purchase_plan_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-plans/{purchase_plan_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Purchase Plan Items */
        get: operations["get_purchase_plan_items_purchase_plans__purchase_plan_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-plans/{purchase_plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Purchase Plan */
        post: operations["approve_purchase_plan_purchase_plans__purchase_plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Overview */
        get: operations["get_dashboard_overview_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIChatRequest */
        AIChatRequest: {
            /** Message */
            message: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "AVAILABLE" | "LOW_STOCK" | "OUT_OF_STOCK";
        /**
         * ConsumptionTrend
         * @enum {string}
         */
        ConsumptionTrend: "DECREASING" | "STABLE" | "INCREASING";
        /** CreateInventoryMovementSchema */
        CreateInventoryMovementSchema: {
            movement_type: components["schemas"]["InventoryMovementType"];
            owner_type: components["schemas"]["InventoryOwnerType"];
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Reason */
            reason?: string | null;
            /** Quantity */
            quantity: number | string;
        };
        /** CreateMaterialSchema */
        CreateMaterialSchema: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            material_type: components["schemas"]["MaterialType"];
            unit_type: components["schemas"]["UnitType"];
            /** Initial Stock */
            initial_stock: number | string;
            /** Initial Minimum Stock */
            initial_minimum_stock: number | string;
        };
        /** CreateProductSchema */
        CreateProductSchema: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Initial Stock */
            initial_stock: number | string;
            /** Initial Minimum Stock */
            initial_minimum_stock: number | string;
        };
        /** CreatePurchasePlanSchema */
        CreatePurchasePlanSchema: {
            /** Items */
            items: components["schemas"]["PurchasePlanItemCreateSchema"][];
        };
        /** CreateSupplierSchema */
        CreateSupplierSchema: {
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Lead Time Days */
            lead_time_days: number;
        };
        /** DashboardOverviewResponse */
        DashboardOverviewResponse: {
            operational_health: components["schemas"]["OperationalHealth"];
            production_readiness: components["schemas"]["ProductionReadiness"];
            inventory_health: components["schemas"]["InventoryHealth"];
            procurement: components["schemas"]["ProcurementSummary"];
            production_risks: components["schemas"]["ProductionRiskSummary"];
            material_coverage: components["schemas"]["MaterialCoverageSummary"];
            supplier_risk: components["schemas"]["SupplierRiskSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InventoryHealth */
        InventoryHealth: {
            materials: components["schemas"]["InventoryHealthSection"];
            products: components["schemas"]["InventoryHealthSection"];
            /** Overall Percentage */
            overall_percentage: number;
            overall_status: components["schemas"]["InventoryHealthStatus"];
        };
        /** InventoryHealthSection */
        InventoryHealthSection: {
            /** Total Items */
            total_items: number;
            /** Available Items */
            available_items: number;
            /** Low Stock Items */
            low_stock_items: number;
            /** Out Of Stock Items */
            out_of_stock_items: number;
            /** Health Percentage */
            health_percentage: number;
            status: components["schemas"]["InventoryHealthStatus"];
        };
        /**
         * InventoryHealthStatus
         * @enum {string}
         */
        InventoryHealthStatus: "healthy" | "attention" | "critical";
        /** InventoryMovementResponseSchema */
        InventoryMovementResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Inventory Id
             * Format: uuid
             */
            inventory_id: string;
            movement_type: components["schemas"]["InventoryMovementType"];
            /** Previous Quantity */
            previous_quantity: string;
            /** Quantity */
            quantity: string;
            /** New Quantity */
            new_quantity: string;
            /** Owner Name */
            owner_name: string;
            /** Owner Code */
            owner_code: string;
            unit_type: components["schemas"]["UnitType"];
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InventoryMovementType
         * @enum {string}
         */
        InventoryMovementType: "IN" | "OUT" | "ADJUSTMENT";
        /**
         * InventoryOwnerType
         * @enum {string}
         */
        InventoryOwnerType: "PRODUCT" | "MATERIAL";
        /** MaterialCoverageRisk */
        MaterialCoverageRisk: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /** Material Sku */
            material_sku: string;
            /** Current Stock */
            current_stock: string;
            /** Average Daily Consumption */
            average_daily_consumption: string;
            /** Days Of Stock */
            days_of_stock: string | null;
            status: components["schemas"]["MaterialCoverageStatus"];
        };
        /**
         * MaterialCoverageStatus
         * @enum {string}
         */
        MaterialCoverageStatus: "critical" | "low" | "healthy" | "no_consumption";
        /** MaterialCoverageSummary */
        MaterialCoverageSummary: {
            /** Materials Tracked */
            materials_tracked: number;
            /** Critical Materials */
            critical_materials: number;
            /** Low Coverage Materials */
            low_coverage_materials: number;
            /** Average Days Of Stock */
            average_days_of_stock: string | null;
            /** Minimum Days Of Stock */
            minimum_days_of_stock: string | null;
            /** Top Risks */
            top_risks: components["schemas"]["MaterialCoverageRisk"][];
        };
        /** MaterialImpactContext */
        MaterialImpactContext: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /** Material Sku */
            material_sku: string;
            impact_level: components["schemas"]["MaterialImpactLevel"];
            /** Current Quantity */
            current_quantity: string;
            /** Minimum Quantity */
            minimum_quantity: string;
            /** Total Outbound */
            total_outbound: string;
            /** Outbound Movements */
            outbound_movements: number;
            /** Stock Coverage Days */
            stock_coverage_days: string | null;
            /** Min Lead Time Days */
            min_lead_time_days: number | null;
            /** Affected Products Count */
            affected_products_count: number;
            /** Supplier Count */
            supplier_count: number;
        };
        /**
         * MaterialImpactLevel
         * @enum {string}
         */
        MaterialImpactLevel: "LOW" | "MEDIUM" | "HIGH";
        /** MaterialProductResponse */
        MaterialProductResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Product Sku */
            product_sku: string;
            /** Quantity */
            quantity: string;
        };
        /** MaterialResponseSchema */
        MaterialResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            unit: components["schemas"]["UnitType"];
            /** Stock */
            stock: string;
            /** Minimum Stock */
            minimum_stock: string;
            status: components["schemas"]["Status"];
            availability_status: components["schemas"]["AvailabilityStatus"];
        };
        /** MaterialSupplierResponse */
        MaterialSupplierResponse: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
            /** Supplier Email */
            supplier_email: string | null;
            /** Supplier Phone */
            supplier_phone: string | null;
            /** Lead Time Days */
            lead_time_days: number;
            /** Supplier Sku */
            supplier_sku: string | null;
            /** Unit Price */
            unit_price: string | null;
            /** Preferred */
            preferred: boolean;
        };
        /**
         * MaterialType
         * @enum {string}
         */
        MaterialType: "RAW_MATERIAL" | "ACCESSORY" | "PACKAGING" | "CONSUMABLE";
        /** OperationalHealth */
        OperationalHealth: {
            /** Score */
            score: number;
            status: components["schemas"]["OperationalStatus"];
            /** Issues Requiring Attention */
            issues_requiring_attention: number;
            /** Low Stock Materials */
            low_stock_materials: number;
            /** Out Of Stock Materials */
            out_of_stock_materials: number;
            /** High Risk Products */
            high_risk_products: number;
            /** Medium Risk Products */
            medium_risk_products: number;
            /** Pending Purchase Plans */
            pending_purchase_plans: number;
        };
        /**
         * OperationalStatus
         * @enum {string}
         */
        OperationalStatus: "healthy" | "attention" | "critical";
        /** PaginatedResponseSchema[InventoryMovementResponseSchema] */
        PaginatedResponseSchema_InventoryMovementResponseSchema_: {
            /** Items */
            items: components["schemas"]["InventoryMovementResponseSchema"][];
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /** Current Page */
            current_page: number;
        };
        /** PaginatedResponseSchema[MaterialResponseSchema] */
        PaginatedResponseSchema_MaterialResponseSchema_: {
            /** Items */
            items: components["schemas"]["MaterialResponseSchema"][];
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /** Current Page */
            current_page: number;
        };
        /** PaginatedResponseSchema[ProductResponseSchema] */
        PaginatedResponseSchema_ProductResponseSchema_: {
            /** Items */
            items: components["schemas"]["ProductResponseSchema"][];
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /** Current Page */
            current_page: number;
        };
        /** PaginatedResponseSchema[PurchasePlanResponseSchema] */
        PaginatedResponseSchema_PurchasePlanResponseSchema_: {
            /** Items */
            items: components["schemas"]["PurchasePlanResponseSchema"][];
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /** Current Page */
            current_page: number;
        };
        /** PaginatedResponseSchema[SupplierResponseSchema] */
        PaginatedResponseSchema_SupplierResponseSchema_: {
            /** Items */
            items: components["schemas"]["SupplierResponseSchema"][];
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /** Current Page */
            current_page: number;
        };
        /** ProcurementAction */
        ProcurementAction: {
            /**
             * Purchase Plan Id
             * Format: uuid
             */
            purchase_plan_id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
            /** Quantity */
            quantity: string;
            /** Estimated Cost */
            estimated_cost: string;
            /** Lead Time Days */
            lead_time_days: number;
            status: components["schemas"]["PurchasePlanStatus"];
            priority: components["schemas"]["ProcurementPriority"];
        };
        /**
         * ProcurementPriority
         * @enum {string}
         */
        ProcurementPriority: "critical" | "high" | "normal";
        /** ProcurementSummary */
        ProcurementSummary: {
            /** Draft Purchase Plans */
            draft_purchase_plans: number;
            /** Approved Purchase Plans */
            approved_purchase_plans: number;
            /** Pending Purchase Plans */
            pending_purchase_plans: number;
            /** Materials To Replenish */
            materials_to_replenish: number;
            /** Estimated Pending Cost */
            estimated_pending_cost: string;
            /** Critical Materials */
            critical_materials: number;
            /** Top Actions */
            top_actions: components["schemas"]["ProcurementAction"][];
        };
        /** ProductMaterialResponse */
        ProductMaterialResponse: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /** Material Sku */
            material_sku: string;
            material_type: components["schemas"]["MaterialType"];
            unit_type: components["schemas"]["UnitType"];
            /** Quantity */
            quantity: string;
        };
        /** ProductResponseSchema */
        ProductResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Stock */
            stock: string;
            /** Minimum Stock */
            minimum_stock: string;
            status: components["schemas"]["Status"];
            availability_status: components["schemas"]["AvailabilityStatus"];
        };
        /** ProductionReadiness */
        ProductionReadiness: {
            /** Total Products */
            total_products: number;
            /** Low Risk Products */
            low_risk_products: number;
            /** Medium Risk Products */
            medium_risk_products: number;
            /** High Risk Products */
            high_risk_products: number;
            /** Critical Risk Products */
            critical_risk_products: number;
            /** Readiness Percentage */
            readiness_percentage: number;
        };
        /** ProductionRiskAnalysisSchema */
        ProductionRiskAnalysisSchema: {
            /** Analysis Period Days */
            analysis_period_days: number;
            /** Products Analyzed */
            products_analyzed: number;
            /** High Risk Products */
            high_risk_products: number;
            /** Medium Risk Products */
            medium_risk_products: number;
            /** Low Risk Products */
            low_risk_products: number;
            /** Products */
            products: components["schemas"]["ProductionRiskProductSchema"][];
            /** Critical Risk Products */
            critical_risk_products?: number | null;
        };
        /** ProductionRiskFactorSchema */
        ProductionRiskFactorSchema: {
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Factor */
            factor: string;
            severity: components["schemas"]["ProductionRiskLevel"];
            /** Value */
            value?: string | null;
            /** Description */
            description: string;
        };
        /**
         * ProductionRiskLevel
         * @enum {string}
         */
        ProductionRiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** ProductionRiskMaterialSchema */
        ProductionRiskMaterialSchema: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /** Material Sku */
            material_sku: string;
            unit_type: components["schemas"]["UnitType"];
            /** Current Stock */
            current_stock: string;
            /** Minimum Stock */
            minimum_stock: string;
            /** Required Per Product */
            required_per_product: string;
            /** Producible Units */
            producible_units: string;
            /** Average Daily Consumption */
            average_daily_consumption: string;
            /** Days Of Stock */
            days_of_stock: string | null;
            stock_status: components["schemas"]["AvailabilityStatus"];
            consumption_trend: components["schemas"]["ConsumptionTrend"];
            /** Suppliers */
            suppliers: components["schemas"]["ProductionRiskSupplierSchema"][];
        };
        /** ProductionRiskOverviewItem */
        ProductionRiskOverviewItem: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Product Sku */
            product_sku: string;
            /** Current Producible Units */
            current_producible_units: string;
            risk_level: components["schemas"]["ProductionRiskLevel"];
            /** Bottleneck Material Name */
            bottleneck_material_name: string | null;
        };
        /** ProductionRiskProductSchema */
        ProductionRiskProductSchema: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Product Sku */
            product_sku: string;
            /** Current Producible Units */
            current_producible_units: string;
            risk_level: components["schemas"]["ProductionRiskLevel"];
            /** Risk Factors */
            risk_factors: components["schemas"]["ProductionRiskFactorSchema"][];
            bottleneck_material: components["schemas"]["ProductionRiskMaterialSchema"] | null;
            /** Risk Materials */
            risk_materials: components["schemas"]["ProductionRiskMaterialSchema"][];
        };
        /** ProductionRiskSummary */
        ProductionRiskSummary: {
            /** Products Analyzed */
            products_analyzed: number;
            /** Low Risk Products */
            low_risk_products: number;
            /** Medium Risk Products */
            medium_risk_products: number;
            /** High Risk Products */
            high_risk_products: number;
            /** Critical Risk Products */
            critical_risk_products: number;
            /** Top Risks */
            top_risks: components["schemas"]["ProductionRiskOverviewItem"][];
        };
        /** ProductionRiskSupplierSchema */
        ProductionRiskSupplierSchema: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
            /** Lead Time Days */
            lead_time_days: number;
            /** Unit Price */
            unit_price: string;
            /** Preferred */
            preferred: boolean;
        };
        /** PurchasePlanItem */
        PurchasePlanItem: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
            /** Quantity */
            quantity: string;
            unit_type: components["schemas"]["UnitType"];
            /** Unit Price */
            unit_price: string;
            /** Estimated Cost */
            estimated_cost: string;
            /** Lead Time Days */
            lead_time_days: number;
            /** Preferred Supplier */
            preferred_supplier: boolean;
        };
        /** PurchasePlanItemCreateSchema */
        PurchasePlanItemCreateSchema: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Quantity */
            quantity: number | string;
        };
        /** PurchasePlanResponseSchema */
        PurchasePlanResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["PurchasePlanStatus"];
            /** Total Estimated Cost */
            total_estimated_cost: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PurchasePlanStatus
         * @enum {string}
         */
        PurchasePlanStatus: "draft" | "approved" | "cancelled";
        /** RagQuerySchema */
        RagQuerySchema: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Similarity Threshold
             * @default 0.75
             */
            similarity_threshold: number;
        };
        /** ReplaceMaterialSupplierItemSchema */
        ReplaceMaterialSupplierItemSchema: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Sku */
            supplier_sku?: string | null;
            /** Unit Price */
            unit_price?: number | string | null;
            /**
             * Preferred
             * @default false
             */
            preferred: boolean;
        };
        /** ReplaceProductMaterialItemSchema */
        ReplaceProductMaterialItemSchema: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Quantity */
            quantity: number | string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high" | "critical";
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE" | "INACTIVE";
        /** SupplierMaterialResponse */
        SupplierMaterialResponse: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /** Material Sku */
            material_sku: string;
            material_type: components["schemas"]["MaterialType"];
            unit_type: components["schemas"]["UnitType"];
            /** Supplier Sku */
            supplier_sku: string | null;
            /** Unit Price */
            unit_price: string | null;
            /** Preferred */
            preferred: boolean;
        };
        /** SupplierResponseSchema */
        SupplierResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Lead Time Days */
            lead_time_days: number;
            status: components["schemas"]["Status"];
        };
        /** SupplierRiskOverviewItem */
        SupplierRiskOverviewItem: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
            /** Lead Time Days */
            lead_time_days: number;
            /** Affected Materials */
            affected_materials: number;
            /** Critical Materials */
            critical_materials: number;
            /** High Risk Materials */
            high_risk_materials: number;
            risk_level: components["schemas"]["RiskLevel"];
        };
        /** SupplierRiskSummary */
        SupplierRiskSummary: {
            /** Total Suppliers */
            total_suppliers: number;
            /** Suppliers At Risk */
            suppliers_at_risk: number;
            /** Critical Risks */
            critical_risks: number;
            /** High Risks */
            high_risks: number;
            /** Medium Risks */
            medium_risks: number;
            /** Low Risks */
            low_risks: number;
            /** Top Risks */
            top_risks: components["schemas"]["SupplierRiskOverviewItem"][];
        };
        /**
         * UnitType
         * @enum {string}
         */
        UnitType: "UNIT" | "KG" | "G" | "M" | "M2" | "L" | "BOX" | "ROLL";
        /** UpdatePurchasePlanItemSchema */
        UpdatePurchasePlanItemSchema: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Quantity */
            quantity: number | string;
        };
        /** UpdatePurchasePlanSchema */
        UpdatePurchasePlanSchema: {
            /** Items */
            items: components["schemas"]["UpdatePurchasePlanItemSchema"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_materials_materials__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                query?: string | null;
                unit_type?: components["schemas"]["UnitType"] | null;
                availability_status?: components["schemas"]["AvailabilityStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseSchema_MaterialResponseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_material_materials__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMaterialSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_by_id_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inventory_movements_inventory_movements__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                query?: string | null;
                movement_type?: components["schemas"]["InventoryMovementType"] | null;
                owner_type?: components["schemas"]["InventoryOwnerType"] | null;
                owner_id?: string | null;
                created_from?: string | null;
                created_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseSchema_InventoryMovementResponseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_inventory_movement_inventory_movements__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInventoryMovementSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_products__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                query?: string | null;
                availability_status?: components["schemas"]["AvailabilityStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseSchema_ProductResponseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_products__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["CreateProductSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_by_id_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suppliers_suppliers__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                query?: string | null;
                status?: components["schemas"]["Status"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseSchema_SupplierResponseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_suppliers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupplierSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_by_id_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_suppliers__supplier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_suppliers_materials__material_id__suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialSupplierResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_material_suppliers_materials__material_id__suppliers_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceMaterialSupplierItemSchema"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferred_supplier_materials__material_id__preferred_supplier_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialSupplierResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_materials_suppliers__supplier_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierMaterialResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_materials_products__product_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMaterialResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_product_materials_products__product_id__materials_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceProductMaterialItemSchema"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_products_materials__material_id__products_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_ai_rag_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagQuerySchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_ai_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_production_risk_production_risk_analyze_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionRiskAnalysisSchema"];
                };
            };
        };
    };
    analyze_material_impact_material_impact_analyze__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialImpactContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_purchase_plan_purchase_plans_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_purchase_plans_purchase_plans__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseSchema_PurchasePlanResponseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_purchase_plan_purchase_plans__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchasePlanSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_purchase_plan_by_id_purchase_plans__purchase_plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_purchase_plan_purchase_plans__purchase_plan_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePurchasePlanSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_purchase_plan_items_purchase_plans__purchase_plan_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchasePlanItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_purchase_plan_purchase_plans__purchase_plan_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_overview_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
        };
    };
}
